config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'home/about'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success mt-3" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="container bg-secondary p-5 mb-3" id="<%= dom_id friend %>">
  <div class="mb-3">
  <h1 class='d-inline fs-1 text-capitalize'>
    <%= friend.first_name %>
  </h1>
  <h3 class="d-inline">
   <%= friend.last_name %>
  </h3>
  </div>

  <p>
    <p class="fs-4 d-inline"><%= friend.email %></p>
  </p>

  <p>
    <p class="fs-4" ><%= friend.phone %></p>
  </p>

  <p>
    <p class="fs-4"><%= friend.twitter %></p>
  </p>


</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend ,class:"btn btn-primary" %> 
  <%= link_to "Back to friends", friends_path ,class:"btn btn-primary" %>
</div>

app/views/friends/index.html.erb
<% if notice %>
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>
<% end %>


<h1>Friend List</h1>

<div id="friends">
<table class="table">
  <thead>
    <tr>
      <th scope="col">First name:</th>
      <th scope="col">Last name:</th>
      <th scope="col">Email:</th>
      <th scope="col">Phone:</th>
      <th scope="col">Twitter:</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
   <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name  %></td>
        <td><%= friend.last_name %></td>
        <td><%=  friend.email %> </td>
        <td> <%= friend.phone  %> </td>
        <td><%=  friend.twitter %> </td>
        <td>    <%= link_to "Show this friend", friend,class:'btn btn-primary' %></td>
      </tr>
    <p>
    </p>
  <% end %>
  </tbody>
</table>
 
</div>

<%= link_to "New friend", new_friend_path,class:'btn btn-secondary' %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-primary" %>
</div>

app/views/friends/show.html.erb
<% if notice %>
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>
<% end %>


<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend),class:"btn btn-secondary " %> 
  <%= link_to "Back to friends", friends_path,class:"btn btn-primary" %>

  <%= button_to "Destroy this friend", @friend, method: :delete,class:"btn btn-danger mt-3" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon navbar-light"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
        </li>
         <li class="nav-item">
        <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1 class="text-center">Project created with this course:</h1>
<div class="container d-flex justify-content-center mt-5">
  <iframe  width="50%" height="360px"  src="https://www.youtube.com/embed/fmyvWz5TUWg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first Rails Webpage...

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "home/header"  %>
  <div class='container'>
     <br>
    <%= yield %>
  </div>
  </body>
</html>